Tabs

diff --git a/push b/push
--- a/push
+++ b/push
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
 exit_on_error() {
-    exit_code=$1
-    last_command=${@:2}
-    if [ $exit_code -ne 0 ]; then
-        >&2 echo "\"${last_command}\" command failed with exit code ${exit_code}."
-        exit $exit_code
-    fi
+	exit_code=$1
+	last_command=${@:2}
+	if [ $exit_code -ne 0 ]; then
+		>&2 echo "\"${last_command}\" command failed with exit code ${exit_code}."
+		exit $exit_code
+	fi
 }
 
 hugo_root="$(dirname "$0")"
